Alter table HocPhan add constraint HP_HTthi foreign key (MaHinhThucThi) references HinhThucThi (MaHinhThucThi)
Alter table LopHP add constraint LopHP_HP foreign key (MaHP) references HocPhan(MaHP)
Alter table ChiTietLopHP add constraint ChiTiet_LopHP foreign key(MaLopHP) references LopHP (MaLopHP)
Alter table LopEng add constraint Eng_LoaiENG foreign key (MaLoaiLopEng) references LoaiLopEng(MaLoaiLopEng)
Alter table DinhMucDayEng add constraint DM_LoaiEng foreign key (MaLoaiLopEng) references LoaiLopEng(MaLoaiLopEng)
Alter table DayEng add constraint DayE_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table DayEng add constraint DayE_LopE foreign key (MaLopEng) references LopEng(MaLopEng)
Alter table ChiTietLopTD add constraint ChiTiet_LopTD foreign key(MaLopTD) references LopTheDuc (MaLopTD)
Alter table Day_BoiDuongTD add constraint DayTD_GV foreign key (MaGV) references GiaoVien (MaGV)
Alter table Day_BoiDuongTD add constraint DayTD_LopTD foreign key (MaLopTD) references LopTheDuc(MaLopTD)
Alter table LopChuyenNganh add constraint LCN_Dtao foreign key (MaLoaiHinhDtao) references LoaiHinhDtao(MaLoaiHinhDtao)
Alter table GiangDayLT add constraint GD_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table GiangDayLT add constraint GD_LHP foreign key (MaLopHP) references LopHP(MaLopHP)
Alter table DMdayBTL add constraint DMDBTL_LoaiBTL foreign key (MaLoaiBTL) references LoaiBTL(MaLoaiBTL)
Alter table DMdayBTL add constraint DMDBTL_LoaiDMDBTL foreign key (MaLoaiDMdayBTL) references LoaiDMdayBTL(MaLoaiDMdayBTL)
Alter table DayVeKT add constraint DVKT_GV foreign key (MaGV) references GiaoVien (MaGV)
Alter table DayVeKT add constraint DVKT_LopKT foreign key (MaLopKT) references LopDayVeKT(MaLopKT)
Alter table DayPhuDao add constraint DayPD_GV foreign key (MaGV) references GiaoVien (MaGV)
Alter table DayPhuDao add constraint DayPD_LopPD foreign key (MaLopPD) references LopPhuDao (MaLopPD)
Alter table DayPhuDao add constraint DayPD_LopHP foreign key (MaLopHP) references LopHP (MaLopHP)
Alter table DayPhuDao add constraint DayPD_HP foreign key (MaHP) references HocPhan(MaHP)
Alter table TongDMGD_CMKT add constraint TongDM_CMNV foreign key (MaChucDanh) references ChucDanhCMNV (MaChucDanh)
Alter table TongDMGD_HH add constraint TongDM_HH foreign key (MaHocHam) references HocHam(MaHocHam)
Alter table BTL_TapBai15t add constraint BTL_LoaiBTL foreign key (MaloaiBTL) references LoaiBTL (MaLoaiBTL)
Alter table LamBTL add constraint LamBTL_LopHP foreign key (MaLopHP) references LopHP (MaLopHP)
Alter table HDBT add constraint HDBT_GV foreign key (MaGV) references GiaoVien (MaGV)
Alter table HDBT add constraint HDBT_LpHP foreign key(MaLopHP) references LopHP (MaLopHP)
Alter table BT_baiKT_TN_TH_TL add constraint BT_LopHP foreign key (MaLopHP) references LopHP (MaLopHP)
Alter table DayBTL add constraint DayBTL_GV foreign key (MaGV) references GiaoVien (MaGV)
Alter table DayBTL add constraint DayBTL_LpHP foreign key (MaLopHP) references LopHP(MaLopHP)
Alter table BTL_TapBai15t add constraint BTL_HP foreign key (MaHP) references HocPhan (MaHP)



