Alter table GiaoVien add constraint GV_BM foreign key (MaBM) references BoMon(MaBM)
Alter table NhanHocHam add constraint NhanHH_HH foreign key (MaHocHam) references HocHam(MaHocHam)
Alter table NhanHocHam add constraint NhanHH_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table NhanCVdang add constraint NhanCVdang_CV foreign key (MaChucVu) references ChucVuDang(MaChucVu)
Alter table NhanCVdang add constraint NhanCVdang_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table NhanHocVi add constraint NhanHV_HV foreign key (MaHocVi) references HocVi(MaHocVi)
Alter table NhanHocVi add constraint NhanHV_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table NhanChucDanhCMNV add constraint NhanChucDanh_CMNV foreign key (MaChucDanh) references ChucDanhCMNV(MaChucDanh)
Alter table NhanChucDanhCMNV add constraint NhanChucDanh_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table BoMon add constraint BM_Khoa foreign key (MaKhoa) references Khoa(MaKhoa)
Alter table ChucVuBM add constraint CVBM_BM foreign key (MaBM) references BoMon(MaBM)
Alter table ChucVuBM add constraint CVBM_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table ChucVuKhoa add constraint CVKhoa_Khoa foreign key (MaKhoa) references Khoa(MaKhoa)
Alter table ChucVuKhoa add constraint CVKhoa_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table TongDinhMucNCKH_HH add constraint DM_HH foreign key (MaHocHam) references HocHam(MaHocHam)
Alter table TongDinhMucNCKH_CMKT add constraint DM_CMKT foreign key (MaChucDanh) references ChucDanhCMNV(MaChucDanh)
Alter table CVkhoa_MienGiam add constraint MienGiam_Khoa foreign key (MaCVkhoa) references ChucVuKhoa(MaCVkhoa)
Alter table CVbm_MienGiam add constraint MienGiam_BM foreign key (MaCVbm) references ChucVuBM(MaCVbm)
Alter table DinhMucMienGiam add constraint MienGiam_Dang foreign key (MaCVdang) references ChucVuDang(MaChucVu)
alter table NhanCVBM add constraint NCVBM_CVBM foreign key (MaCVbm) references ChucVuBM (MaCVbm)
alter table NhanCVBM add constraint NCVBM_BM foreign key (MaBM) references BoMon (MaBM)

