Alter table NghienCuuDTKH add constraint NCKH_ĐTKH foreign key (MaCT) references DeTaiKH (MaCT)
Alter table NghienCuuDTKH add constraint NCKH_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table TinhTrangCTKH add constraint TTCTKH_CTKH foreign key (MaCT) references DeTaiKH(MaCT)
Alter table DinhMucNCKH add constraint ĐMNCKH_ĐTKH foreign key (MaCT) references DeTaiKH(MaCT)
Alter table DinhMucNCKH add constraint ĐMNCKH_CĐT foreign key (MaCapDT) references CapĐT(MaCapDT) 
Alter table ThamGiaBaoCaoKH add constraint TGBCKH_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table ThamGiaBaoCaoKH add constraint TGBCKH_BaoCao foreign key (MaBaoCao) references BaoCaoKH(MaBaoCao)
Alter table ThamGiaBaiBaoKH add constraint TGBBKH_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table ThamGiaBaiBaoKH add constraint TGBBKH_BaiBao foreign key (MaBaiBao) references BaiBaoKH(MaBaiBao)
Alter table ĐăngBaiBao add constraint ĐBB_TapChi foreign key (MaTapChi) references TapChi (MaTapChi)
Alter table ĐăngBaiBao add constraint ĐBB_BaiBao foreign key (MaBaiBao) references BaiBaoKH(MaBaiBao)
Alter table ĐăngBaoCao add constraint ĐBC_HoiNghi foreign key (MaHoiNghi) references HoiNghiKH(MaHoiNghi)
Alter table ĐăngBaoCao add constraint ĐBC_BaoCao foreign key (MaBaoCao) references BaoCaoKH(MaBaoCao)
Alter table DeTaiKH add constraint DTKH_CapDT foreign key (MaCapDT) references CapĐT (MaCapDT)

Alter table HoiNghiKH add constraint HNKH_DMBB foreign key (MaLoaiHoiNghi) references ĐMBaoCao (MaLoaiHoiNghi)
Alter table TapChi add constraint TC_DMBC foreign key (MaLoaiTapChi) references ĐMBaiBao (MaLoaiTapChi)
Alter table Sach add constraint Sach_LSach foreign key (MaLoaiSach) references LoaiSach (MaLoaiSach)
Alter table VietSach add constraint VS_GV foreign key (MaGV) references GiaoVien (MaGV)
Alter table VietSach add constraint VS_Sach foreign key (MaSach) references Sach (MaSach)
Alter table XuatBan add constraint XB_NXB foreign key (MaNXB) references NhaXB (MaNXB)
Alter table XuatBan add constraint XB_Sach foreign key (MaSach) references Sach (MaSach)
Alter table GiaiThuongKHCN add constraint GTKH_LGT foreign key (MaLoaiGiaiThuong) references LoaiGiaiThuong (MaLoaiGiaiThuong)
Alter table NhanGiaiThuong add constraint NGT_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table NhanGiaiThuong add constraint NGT_GTKH foreign key (MaGiaiThuong) references GiaiThuongKHCN (MaGiaiThuong)
Alter table BangPhatMinh add constraint BPM_LVB foreign key (MaLoaiVB) references LoaiVB (MaLoaiVB)
Alter table CapVanBang add constraint CVB_VB foreign key (MaVanBang) references BangPhatMinh(MaVanBang)
Alter table CapVanBang add constraint CVB_GV foreign key (MaGV) references GiaoVien(MaGV)
Alter table SanPhamKHCN add constraint SPKH_ĐTKH foreign key (MaCT) references DeTaiKH(MaCT)
Alter table UngDungSPKH add constraint UDSPKH_SPKH foreign key (MaSP) references SanPhamKHCN (MaSP)
Alter table UngDungSPKH add constraint UDSPKH_ĐC foreign key (MaDiaChi) references NoiUngDungSPKH (MaDiaChi)


